### ISSUE TITLE
Failed to handle HTTP request: Invalid version string: 1.2.x

### ISSUE THREAD

**Issue by Slushe** [hai-vr/prefabulous-avatar#1]
When I try to install prefabulous-avatar 1.6.0 through VCC it fails to check for package changes with ndmf

```
2023-12-30 23:07:35.029 -08:00 [INF] Dependency list upgrading nadena.dev.ndmf from 1.2.x to 1.2.x
2023-12-30 23:07:35.035 -08:00 [ERR] Failed to handle HTTP request: Invalid version string: 1.2.x
2023-12-30 23:07:35.137 -08:00 [INF] Failed to check for package changes: 500

```

I already have 1.2.5 of Non-Destructive Modular Framework in my project through VCC.

Unity 2022.3.6f1
VCC v2.2.3

**Comment by hai-vr** [comment]
Could you please try to install the `Animator As Code - NDMF Processor` package first in VCC, and then `Haï ~ Prefabulous Avatar` next?

It looks like it might be hitting an issue in Creator Companion but I'm not sure.

**Comment by Slushe** [comment]
Yeah that is already in my project. Still the same 500 response code.

![CreatorCompanion_2023-12-31_12-36-23](https://github.com/hai-vr/prefabulous-avatar/assets/12984836/6982d3e1-880c-4d5a-b9a4-e1816ce6dfbc)

**Comment by Slushe** [comment]
Okay I got it working.

Had to completely remove repository listings for Modular-Avatar and Prefabulous and re-add them back to VCC before it let me install it properly. None of the links to the repositories changed at all. Makes no sense that this worked.
