### ISSUE TITLE
Generate Twist Bones (Alpha) - Invalid URL when clicking the help button

### ISSUE THREAD

**Issue by WillyB1337** [hai-vr/prefabulous-avatar#5]
![image](https://github.com/hai-vr/prefabulous-avatar/assets/16364065/e2515d2e-b012-47b3-9999-c0fd2f1a5974)
![image](https://github.com/hai-vr/prefabulous-avatar/assets/16364065/99dad790-51a2-4b70-86f8-1e6fcb9cf819)

**Comment by hai-vr** [comment]
Will be fixed by 7eb473e
