### ISSUE TITLE
Reverts latest VRChat SDK 3.6.1 to 3.6.0-beta.1 after installing

### ISSUE THREAD

**Issue by Shii2** [hai-vr/prefabulous-avatar#6]
Installing latest version of Prefabulous Avatar downgrades VRChat Base and Avatars SDK from version 3.6.1 to 3.6.0-beta.1

**Comment by hai-vr** [comment]
Fixed in 6a24545
Released in [2.0.0](https://github.com/hai-vr/prefabulous-avatar/releases/tag/2.0.0)
